

# coding: utf-8
from sqlalchemy import BigInteger, Column, DateTime, Integer, Numeric, SmallInteger, String, Table, Text, text
from sqlalchemy.dialects.mysql.base import LONGBLOB
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()
metadata = Base.metadata


class MAC_CREDITRMB(Base):
    __tablename__ = "MAC_CREDITRMB"

    SGNMONTH = Column(String(14, u'utf8_bin'), primary_key=True)
    TOTALDEPOSIT = Column(Numeric(18, 4))
    CORPORATEDEPOSIT = Column(Numeric(18, 4))
    CORPORATEDEMANDDEPOSIT = Column(Numeric(18, 4))
    CORPORATETIMEDEPOSIT = Column(Numeric(18, 4))
    NOTICEDEPOSIT = Column(Numeric(18, 4))
    MARGINDEPOSIT = Column(Numeric(18, 4))
    PERSONALDEPOSIT = Column(Numeric(18, 4))
    SAVINGDEPOSIT = Column(Numeric(18, 4))
    DEMANDDEPOSIT = Column(Numeric(18, 4))
    TIMEDEPOSIT = Column(Numeric(18, 4))
    PERSONALMARGINDEPOSIT = Column(Numeric(18, 4))
    PERSONALSTRUCTUREDEPOSIT = Column(Numeric(18, 4))
    FISCALDEPOSIT = Column(Numeric(18, 4))
    GOVERNMENTDEPOSIT = Column(Numeric(18, 4))
    RURALDEPOSIT = Column(Numeric(18, 4))
    TEMPORARYDEPOSIT = Column(Numeric(18, 4))
    DESIGNATEDDEPOSIT = Column(Numeric(18, 4))
    OTHERDEPOSIT = Column(Numeric(18, 4))
    FINANCEBOND = Column(Numeric(18, 4))
    M0 = Column(Numeric(18, 4))
    FINANCELIABILITY = Column(Numeric(18, 4))
    OTHERITEM = Column(Numeric(18, 4))
    TOTALFUNDSOURCE = Column(Numeric(18, 4))
    TOTALLOAN = Column(Numeric(18, 4))
    DOMESTICLOAN = Column(Numeric(18, 4))
    SHORTTERMLOAN = Column(Numeric(18, 4))
    INDUSTRYLOAN = Column(Numeric(18, 4))
    COMMERCELOAN = Column(Numeric(18, 4))
    CONSTRUCTLOAN = Column(Numeric(18, 4))
    AGRICULTURELOAN = Column(Numeric(18, 4))
    OTHERSHORTTERMLOAN = Column(Numeric(18, 4))
    MEDIUMLONGTERMLOAN = Column(Numeric(18, 4))
    DESIGNATELOAN = Column(Numeric(18, 4))
    OTHERLOAN = Column(Numeric(18, 4))
    FINANCELEASE = Column(Numeric(18, 4))
    BILLFINANCE = Column(Numeric(18, 4))
    ADVANCE = Column(Numeric(18, 4))
    OVERSEALOAN = Column(Numeric(18, 4))
    PORTFOLIOINVEST = Column(Numeric(18, 4))
    SECURITY = Column(Numeric(18, 4))
    OTHERSHARE = Column(Numeric(18, 4))
    BULLIONPURCHASE = Column(Numeric(18, 4))
    FOREXPURCHASE = Column(Numeric(18, 4))
    TREASURYADVANCE = Column(Numeric(18, 4))
    FINANCEASSETS = Column(Numeric(18, 4))
    TOTALFUNDUSE = Column(Numeric(18, 4))
    DOMESTICDEPOSIT = Column(Numeric(18, 4))
    HOUSEHOLDDEPOSIT = Column(Numeric(18, 4))
    HOUSEHOLDDEMANDDEPOSIT = Column(Numeric(18, 4))
    HOUSEHOLDTIMEDEPOSIT = Column(Numeric(18, 4))
    NONFINANCEDEPOSIT = Column(Numeric(18, 4))
    NONFINANCEDEMANDDEPOSIT = Column(Numeric(18, 4))
    NONFINANCETIMEDEPOSIT = Column(Numeric(18, 4))
    ORGANIZEDEPOSIT = Column(Numeric(18, 4))
    NONBANKFINANCEDEPOSIT = Column(Numeric(18, 4))
    OVERSEADEPOSIT = Column(Numeric(18, 4))
    HOUSEHOLDLOAN = Column(Numeric(18, 4))
    HOUSEHOLDSHORTTERMLOAN = Column(Numeric(18, 4))
    HOUSEHOLDSHORTCONSUMLOAN = Column(Numeric(18, 4))
    SHORTTERMOPERATLOAN = Column(Numeric(18, 4))
    HOUSEHOLDMIDLONGTERMLOAN = Column(Numeric(18, 4))
    HOUSEHOLDMIDLONGCONSUMLOAN = Column(Numeric(18, 4))
    HOUSEHOLDMIDLONGOPERATLOAN = Column(Numeric(18, 4))
    NONFINANCEORGANIZELOAN = Column(Numeric(18, 4))
    NONFINANCESHORTTERMLOAN = Column(Numeric(18, 4))
    NONFINANCEMIDLONGTERMLOAN = Column(Numeric(18, 4))
    NONBANKFINANCELOAN = Column(Numeric(18, 4))
