

# coding: utf-8
from sqlalchemy import BigInteger, Column, DateTime, Integer, Numeric, SmallInteger, String, Table, Text, text
from sqlalchemy.dialects.mysql.base import LONGBLOB
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()
metadata = Base.metadata


class MAC_INSCOBS(Base):
    __tablename__ = "MAC_INSCOBS"

    SGNYEAR = Column(String(8, u'utf8_bin'), primary_key=True, nullable=False)
    INSTITUTIONID = Column(Numeric(20, 0), primary_key=True, nullable=False)
    SHORTNAME = Column(String(40, u'utf8_bin'))
    FULLNAME = Column(String(200, u'utf8_bin'))
    CASH = Column(Numeric(22, 4))
    SETTLEMENTRESERVES = Column(Numeric(22, 4))
    NOBLEMETAL = Column(Numeric(22, 4))
    LENDINGCAPITAL = Column(Numeric(22, 4))
    TRADINGFINANCIALASSETS = Column(Numeric(22, 4))
    DERFINANCIALASSETS = Column(Numeric(22, 4))
    BACKFINANCIALASSETS = Column(Numeric(22, 4))
    INTERESTRECEIVABLE = Column(Numeric(22, 4))
    PREMIUMRECEIVABLE = Column(Numeric(22, 4))
    SUBROGATIONRECEIVABLE = Column(Numeric(22, 4))
    REINSURANCERECEIVABLE = Column(Numeric(22, 4))
    REUNEXPIREDRECEIVABLE = Column(Numeric(22, 4))
    REUNPAYRECEIVABLE = Column(Numeric(22, 4))
    RELIFERECEIVABLE = Column(Numeric(22, 4))
    RELONGHEALTHRECEIVABLE = Column(Numeric(22, 4))
    INSUREDPLEDGEPAYMENTS = Column(Numeric(22, 4))
    LOANSADVANCES = Column(Numeric(22, 4))
    DEPOSITPAID = Column(Numeric(22, 4))
    INVESTINDEBT = Column(Numeric(22, 4))
    ASSETMANAGEFEES = Column(Numeric(22, 4))
    OTHERRECEIVABLE = Column(Numeric(22, 4))
    FIXEDDEPOSIT = Column(Numeric(22, 4))
    FORSALEFINANCIALASSETS = Column(Numeric(22, 4))
    INVESTTOMATURITY = Column(Numeric(22, 4))
    INVESTINLOANRECEIVABLE = Column(Numeric(22, 4))
    LONGTERMEQUITYINVESTMENT = Column(Numeric(22, 4))
    GOODWILL = Column(Numeric(22, 4))
    REFUNDABLEDEPOSIT = Column(Numeric(22, 4))
    INVESTINPROPERTY = Column(Numeric(22, 4))
    FIXEDASSETS = Column(Numeric(22, 4))
    CONSTRUCTIONINPROGRESS = Column(Numeric(22, 4))
    INTANGIBLEASSETS = Column(Numeric(22, 4))
    SEPARATEACCOUNTASSETS = Column(Numeric(22, 4))
    DEFERREDINCOMETAXASSETS = Column(Numeric(22, 4))
    OTHERASSETS = Column(Numeric(22, 4))
    ASSETS = Column(Numeric(22, 4))
    SHORTTERMLOANS = Column(Numeric(22, 4))
    LOANFROMCENTRALBANK = Column(Numeric(22, 4))
    FINANCIALDEPOSIT = Column(Numeric(22, 4))
    DEPOSITRECEIVED = Column(Numeric(22, 4))
    BORROWINGCAPITAL = Column(Numeric(22, 4))
    TRADINGFINANCIALLIABILITY = Column(Numeric(22, 4))
    DERFINANCIALLIABILITY = Column(Numeric(22, 4))
    REPURCHASEFINANCIALASSETS = Column(Numeric(22, 4))
    ACCEPTDEPOSIT = Column(Numeric(22, 4))
    ACTINGTRADINGSECURITIES = Column(Numeric(22, 4))
    PREMIUMRECEIVED = Column(Numeric(22, 4))
    COMMISSIONPAYABLE = Column(Numeric(22, 4))
    REINSURANCEPAYABLE = Column(Numeric(22, 4))
    PAYROLLPAYABLE = Column(Numeric(22, 4))
    TAXESPAYABLE = Column(Numeric(22, 4))
    OTHERFEEPAYABLE = Column(Numeric(22, 4))
    INTERESTPAYABLE = Column(Numeric(22, 4))
    PAYMENTPAYABLE = Column(Numeric(22, 4))
    POLICYDIVIDENDPAYABLE = Column(Numeric(22, 4))
    INSUREDSAVINGINVESTMENT = Column(Numeric(22, 4))
    UNEXPIREDRESERVES = Column(Numeric(22, 4))
    UNPAYRESERVES = Column(Numeric(22, 4))
    LIFERESERVES = Column(Numeric(22, 4))
    LONGHEALTHRESERVES = Column(Numeric(22, 4))
    LONGTERMLOANS = Column(Numeric(22, 4))
    SUBORDINATEDDEBTPAYABLE = Column(Numeric(22, 4))
    ACCRUEDLIABILITIES = Column(Numeric(22, 4))
    BONDPAYABLE = Column(Numeric(22, 4))
    SEPARATEACCOUNTLIABILITY = Column(Numeric(22, 4))
    DEFERREDINCOMETAXLIABILITY = Column(Numeric(22, 4))
    OTHERLIABILITY = Column(Numeric(22, 4))
    LIABILITY = Column(Numeric(22, 4))
    PAIDINCAPITAL = Column(Numeric(22, 4))
    CAPITALRESERVES = Column(Numeric(22, 4))
    LESSTREASURYSHARE = Column(Numeric(22, 4))
    SURPLUSRESERVES = Column(Numeric(22, 4))
    GENERALRISKPREPARATION = Column(Numeric(22, 4))
    UNDISTRIBUTEDPROFITS = Column(Numeric(22, 4))
    DIFFERENCEFOREIGNCURRENCY = Column(Numeric(22, 4))
    PARENTOWNERSEQUITY = Column(Numeric(22, 4))
    MINORITYEQUITY = Column(Numeric(22, 4))
    OWNERSEQUITY = Column(Numeric(22, 4))
    LIABILITYOWNERSEQUITY = Column(Numeric(22, 4))
