

# coding: utf-8
from sqlalchemy import BigInteger, Column, DateTime, Integer, Numeric, SmallInteger, String, Table, Text, text
from sqlalchemy.dialects.mysql.base import LONGBLOB
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()
metadata = Base.metadata


class MAC_FIXEDASSETSINVESTY(Base):
    __tablename__ = "MAC_FIXEDASSETSINVESTY"

    SGNYEAR = Column(String(8, u'utf8_bin'), primary_key=True)
    FIXEDASSETSINVEST = Column(Numeric(18, 4))
    STATEOWNED = Column(Numeric(18, 4))
    COLLECTIVE = Column(Numeric(18, 4))
    RURALCOLLECTIVE = Column(Numeric(18, 4))
    INDIVIDUAL = Column(Numeric(18, 4))
    RURALINDIVIDUAL = Column(Numeric(18, 4))
    JOINTOWNED = Column(Numeric(18, 4))
    JOINTSTOCK = Column(Numeric(18, 4))
    FOREIGN = Column(Numeric(18, 4))
    HKMACAOTAIWAN = Column(Numeric(18, 4))
    OTHERTYPE = Column(Numeric(18, 4))
    CAPITALCONSTRUCT = Column(Numeric(18, 4))
    INNOVATE = Column(Numeric(18, 4))
    REALESTATE = Column(Numeric(18, 4))
    OTHERINVEST = Column(Numeric(18, 4))
    URBAN = Column(Numeric(18, 4))
    RURAL = Column(Numeric(18, 4))
    FARMHOUSEHOLD = Column(Numeric(18, 4))
    CONSTRUCTINSTALL = Column(Numeric(18, 4))
    EQUIPMENTPURCHASE = Column(Numeric(18, 4))
    OTHEREXPENSE = Column(Numeric(18, 4))
    PRIMARY = Column(Numeric(18, 4))
    SECONDARY = Column(Numeric(18, 4))
    TERTIARY = Column(Numeric(18, 4))
    STATEBUDGET = Column(Numeric(18, 4))
    DOMESTICLOAN = Column(Numeric(18, 4))
    FOREIGNINVEST = Column(Numeric(18, 4))
    SELFRAISEDFUND = Column(Numeric(18, 4))
    OTHERFUND = Column(Numeric(18, 4))
    CONSTRUCT = Column(Numeric(18, 4))
    UNDERCONSTRUCT = Column(Numeric(18, 4))
    NETUNDERCONSTRUCT = Column(Numeric(18, 4))
    CONSTRUCTAREA = Column(Numeric(18, 4))
    RESIDENTCONSTRUCTAREA = Column(Numeric(18, 4))
    COMPLETEAREA = Column(Numeric(18, 4))
    RESIDENTCOMPLETEAREA = Column(Numeric(18, 4))
    FIXEDASSETSINVESTYOY = Column(Numeric(10, 4))
    STATEOWNEDYOY = Column(Numeric(10, 4))
    COLLECTIVEYOY = Column(Numeric(10, 4))
    RURALCOLLECTIVEYOY = Column(Numeric(10, 4))
    INDIVIDUALYOY = Column(Numeric(10, 4))
    RURALINDIVIDUALYOY = Column(Numeric(10, 4))
    JOINTOWNEDYOY = Column(Numeric(10, 4))
    JOINTSTOCKYOY = Column(Numeric(10, 4))
    FOREIGNYOY = Column(Numeric(10, 4))
    HKMACAOTAIWANYOY = Column(Numeric(10, 4))
    OTHERTYPEYOY = Column(Numeric(10, 4))
    CAPITALCONSTRUCTYOY = Column(Numeric(10, 4))
    INNOVATEYOY = Column(Numeric(10, 4))
    REALESTATEYOY = Column(Numeric(10, 4))
    OTHERINVESTYOY = Column(Numeric(10, 4))
    URBANYOY = Column(Numeric(10, 4))
    RURALYOY = Column(Numeric(10, 4))
    FARMHOUSEHOLDYOY = Column(Numeric(10, 4))
    CONSTRUCTINSTALLYOY = Column(Numeric(10, 4))
    EQUIPMENTPURCHASEYOY = Column(Numeric(10, 4))
    OTHEREXPENSEYOY = Column(Numeric(10, 4))
    PRIMARYYOY = Column(Numeric(10, 4))
    SECONDARYYOY = Column(Numeric(10, 4))
    TERTIARYYOY = Column(Numeric(10, 4))
    STATEBUDGETYOY = Column(Numeric(10, 4))
    DOMESTICLOANYOY = Column(Numeric(10, 4))
    FOREIGNINVESTYOY = Column(Numeric(10, 4))
    SELFRAISEDFUNDYOY = Column(Numeric(10, 4))
    OTHERFUNDYOY = Column(Numeric(10, 4))
    CONSTRUCTYOY = Column(Numeric(10, 4))
    UNDERCONSTRUCTYOY = Column(Numeric(10, 4))
    NETUNDERCONSTRUCTYOY = Column(Numeric(10, 4))
    CONSTRUCTAREAYOY = Column(Numeric(10, 4))
    RESIDENTCONSTRUCTAREAYOY = Column(Numeric(10, 4))
    COMPLETEAREAYOY = Column(Numeric(10, 4))
    RESIDENTCOMPLETEAREAYOY = Column(Numeric(10, 4))
