

# coding: utf-8
from sqlalchemy import BigInteger, Column, DateTime, Integer, Numeric, SmallInteger, String, Table, Text, text
from sqlalchemy.dialects.mysql.base import LONGBLOB
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()
metadata = Base.metadata


class STK_EQ_IPO_INFO(Base):
    __tablename__ = "STK_EQ_IPO_INFO"

    INSTITUTIONID = Column(Numeric(20, 0), primary_key=True, nullable=False)
    SECURITYID = Column(Numeric(20, 0), primary_key=True, nullable=False)
    SYMBOL = Column(String(12, u'utf8_bin'))
    EVENTID = Column(String(40, u'utf8_bin'))
    SECURITYTYPEID = Column(String(12, u'utf8_bin'))
    SECURITYTYPE = Column(String(12, u'utf8_bin'))
    ISIPO = Column(String(2, u'utf8_bin'))
    IPO1DECLAREDATE = Column(DateTime)
    SIGNDATE = Column(DateTime)
    IPO2DECLAREDATE = Column(DateTime)
    PUBLICATIONS = Column(String(200, u'utf8_bin'))
    WEBSITE = Column(String(200, u'utf8_bin'))
    ROADSHOWWEBSITE = Column(String(100, u'utf8_bin'))
    ROADSHOWSTARTDATE = Column(DateTime)
    ROADSHOWENDDATE = Column(DateTime)
    STARTDATE = Column(DateTime)
    ENDDATE = Column(DateTime)
    ONLINESTARTDATE = Column(DateTime)
    ONLINEENDDATE = Column(DateTime)
    OFFLINESTARTDATE = Column(DateTime)
    OFFLINEENDDATE = Column(DateTime)
    SECONDARYMARKETISSUEDATE = Column(DateTime)
    IPO3DECLAREDATE = Column(DateTime)
    OTHERISSUEDATE = Column(DateTime)
    CALCULATIONDATE = Column(DateTime)
    IPO4DECLAREDATE = Column(DateTime)
    PUBLICATIONS2 = Column(String(200, u'utf8_bin'))
    WEBSITE2 = Column(String(200, u'utf8_bin'))
    LISTEDDATE = Column(DateTime)
    PARVALUE = Column(Numeric(10, 2))
    CURRENCYCODE = Column(String(12, u'utf8_bin'))
    CURRENCY = Column(String(20, u'utf8_bin'))
    ISSUESHARES = Column(Numeric(20, 0))
    ISSUESHARESPRIVATE = Column(Numeric(20, 0))
    ISSUESHARESPUBLIC = Column(Numeric(20, 0))
    OPTIONSIGN = Column(String(2, u'utf8_bin'))
    PRICE = Column(Numeric(10, 2))
    PRICEPUBLIC = Column(Numeric(10, 2))
    PRICESPECIAL = Column(Numeric(10, 2))
    ISSUEOBJECT = Column(String(1000, u'utf8_bin'))
    ISSUEMODEID = Column(String(100, u'utf8_bin'))
    ISSUEMODE = Column(String(100, u'utf8_bin'))
    PRICEMODEID = Column(String(40, u'utf8_bin'))
    PRICEMODE = Column(String(40, u'utf8_bin'))
    UNDERWRITEDMETHODSID = Column(String(12, u'utf8_bin'))
    UNDERWRITEDMETHODS = Column(String(20, u'utf8_bin'))
    PE1 = Column(Numeric(10, 4))
    PE1CEILING = Column(Numeric(10, 4))
    PE1FLOOR = Column(Numeric(10, 4))
    PE2 = Column(Numeric(10, 4))
    PE2CEILING = Column(Numeric(10, 4))
    PE2FLOOR = Column(Numeric(10, 4))
    PE3 = Column(Numeric(10, 4))
    PE4 = Column(Numeric(10, 4))
    NAV1 = Column(Numeric(10, 4))
    NAV2 = Column(Numeric(10, 4))
    EPS1 = Column(Numeric(10, 4))
    EPS2 = Column(Numeric(10, 4))
    PB = Column(Numeric(10, 4))
    ACTUALISSUESHARES = Column(Numeric(20, 0))
    ACTUALRAISEDSHARESPRIVATE = Column(Numeric(20, 0))
    ACTUALRAISEDSHARESLEGALENTITY = Column(Numeric(20, 0))
    ACTUALRAISEDSHARESSTAFF = Column(Numeric(20, 0))
    ACTUALRAISEDSHARESSPECIAL = Column(Numeric(20, 0))
    ACTUALRAISEDSHARESPUBLIC = Column(Numeric(20, 0))
    EXPECTRAISEFUND = Column(Numeric(20, 2))
    EXPECTRAISENETFUND = Column(Numeric(20, 2))
    EXPECTEXPENSE = Column(Numeric(20, 2))
    RAISEFUND = Column(Numeric(20, 2))
    RAISENETFUND = Column(Numeric(20, 2))
    EXPENSE = Column(Numeric(20, 2))
    EXPENSEPERSHARE = Column(Numeric(10, 4))
    PRICESPECIALINFOREIGN = Column(Numeric(10, 2))
    CURRENCYCODE1 = Column(String(12, u'utf8_bin'))
    CURRENCY1 = Column(String(20, u'utf8_bin'))
    PRICEPUBLICINFOREIGN = Column(Numeric(10, 2))
    CURRENCYCODE2 = Column(String(12, u'utf8_bin'))
    CURRENCY2 = Column(String(20, u'utf8_bin'))
    RAISEFUNDINFOREIGN = Column(Numeric(20, 2))
    RAISENETFUNDINFOREIGN = Column(Numeric(20, 2))
    EXPENSEINFOREIGN = Column(Numeric(20, 2))
    EXPENSEPERSHAREINFOREIGN = Column(Numeric(10, 4))
    REGISTEREDCAPITAL1 = Column(Numeric(20, 2))
    REGISTEREDCAPITAL2 = Column(Numeric(20, 2))
    BANK = Column(String(400, u'utf8_bin'))
    ACCOUNTS = Column(String(400, u'utf8_bin'))
    TAXRATE = Column(Numeric(8, 2))
    TAXRATETYPEID = Column(String(20, u'utf8_bin'))
    TAXRATETYPE = Column(String(20, u'utf8_bin'))
    UPDATETIME_EN = Column(DateTime)
